services:
  scrobgoblin:
    build: .
    image: scrobgoblin:latest
    container_name: scrobgoblin
    restart: unless-stopped
    mem_limit: 128m
    ports:
      - "4567:4567"
    volumes:
      - ./conf:/conf:ro
    command: ["/bin/sh", "-c", "cd /conf && exec /app/scrobgoblin"]
    extra_hosts:
      - "koito.geary.quest:host-gateway"
    networks:
      - proxiable
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxiable"
      # HTTP
      - "traefik.http.routers.scrobgoblin_http.rule=Host(`scrobgoblin.geary.quest`)"
      - "traefik.http.routers.scrobgoblin_http.entrypoints=web"
      - "traefik.http.routers.scrobgoblin_http.middlewares=redirect-to-https@file"
      - "traefik.http.services.scrobgoblin.loadbalancer.server.port=4567"
      # HTTPS
      - "traefik.http.routers.scrobgoblin_https.rule=Host(`scrobgoblin.geary.quest`)"
      - "traefik.http.routers.scrobgoblin_https.entrypoints=websecure"
      - "traefik.http.routers.scrobgoblin_https.tls=true"
      - "traefik.http.routers.scrobgoblin_https.tls.certresolver=cloudflare"
      - "traefik.http.services.scrobgoblin.loadbalancer.server.port=4567"

networks:
  proxiable:
    external: true
